language: python

sudo: false

python:
  - "3.7"

# Match postgresql version to that in conf/pillar/project.sls
services:
  - postgresql

# In general, cache things where they are.
directories:
  - $HOME/.cache/pip
#  - $HOME/.npm
#  - $HOME/.nvm
#  - $HOME/.cache/node_modules
#  - $HOME/.cache/venvs

env:
  - WORKON_HOME=$HOME/.cache/venvs
  - DATABASE_URL=postgres://postgres@localhost:5432/wayne_db
  - SECRET_KEY=thisisasecret

install:
  - pip install -r requirements.txt
#  - pip install -U 'Django>2.0'
#  - mkdir -p $WORKON_HOME
#  - nvm install 10.16.0
#  - nvm use 10.16.0

before_script:
  - psql -c 'create database wayne_db;' -U postgres

script:
  - python manage.py test --noinput
#  - . $WORKON_HOME/test_template/bin/activate


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


