version: '3'

services:

  wayne-app:
    container_name: "wayne-app"
    build: .
    volumes:
      - .:/data/www
    depends_on:
      - wayne-zookeeper
      - wayne-kafka
      - wayne-db
    environment:
      - "DATABASE_URL=postgres://user:password@wayne-db:5432/wayne_db"
      - "SECRET_KEY=thisisasecret"
    ports:
      - "8000:8000"

  wayne-db:
    container_name: "wayne-db"
    image: "postgres:11.5"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - "POSTGRES_DB=wayne_db"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5433:5432"

  wayne-zookeeper:
    container_name: "wayne-zookeeper"
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  wayne-kafka:
    container_name: "wayne-kafka"
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://wayne-kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: wayne-zookeeper:2181
    depends_on:
      - wayne-zookeeper

volumes:
  db-data:
    driver: "local"
